{!! file_get_contents(base_path('docs/api-references/common.md')) !!}
{!! file_get_contents(base_path('docs/api-references/food.md')) !!}
{!! file_get_contents(base_path('docs/api-references/categories.md')) !!}
{!! file_get_contents(base_path('docs/api-references/material.md')) !!}
{!! file_get_contents(base_path('docs/api-references/user.md')) !!}
{!! file_get_contents(base_path('docs/api-references/daily-menus.md')) !!}
{!! file_get_contents(base_path('docs/api-references/order.md')) !!}
{!! file_get_contents(base_path('docs/api-references/statistic.md')) !!}
{!! file_get_contents(base_path('docs/api-references/search-and-with-relations.md')) !!}
